### PR TITLE
micro uprev to 0.12.8

### PR DESCRIPTION
**Pull request by jpalladino84**
## What
- micro uprev to 0.12.8 to transition to Amazon Trust Services (ATS) Certificates

## Why
https://docs.aws.amazon.com/streams/latest/dev/kinesis-kpl-upgrades.html

### CODE REVIEW

**Comment by boneill42** [comment]
Do we want to upgrade to latest?

**Comment by boneill42** [comment]
0.12.18 is available.

**Comment by jpalladino84** [comment]
@boneill42 done. All tests still pass.

**Comment by boneill42** [comment]
cool.  if we are upgrading to 0.2.18, we should probably take the corresponding aws-sdk-core version too.   
https://github.com/awslabs/amazon-kinesis-producer/blob/v0.12.8/java/amazon-kinesis-producer/pom.xml

According to line 60 of that, we should run with: 1.11.245

Can you upgrade that as well?

**Pull request merged**
